### ISSUE TITLE
s3eNOpenFeintAvailable() returns false on iOS

### ISSUE THREAD

**Issue by macieks** [marmalade/openfeint#6]
It seems after adding support for Android, the s3eNOpenFeintAvailable() returns false on iOS now.

FYI, with "Updated code to remove bug where OpenFeintSettingDevelopmentMode ..." change it still works fine.

I've only tested this on my  iPad1 - both my app and example app included with openfeint marmalade lib fail to initialize openfeint extension.

Cheers!

**Comment by faizann** [comment]
Hi

If you look at DeployTool logs, you would notice that ld ignores the lib because it was not compiled with armv6. Hence it doesn't load either in app. This happens on Windows because Marmalade there defaults to armv6 while lib was amrv7 and archive.

I recompiled and pushed the binaries/libs to github with armv6. Kindly test and tell me if this works for you as I don't have a windows PC with me.

**Comment by macieks** [comment]
Thanks for quick fix.

Your change was most likely necessary but I was still getting the same issue after getting latest libs. I fixed it by adding these 2 lines to the s3eNOpenFeint.mkf (seems these were lost at some point):

iphone-link-libs="s3eNOpenFeint " #quotes and space are needed here to separate appended options
iphone-link-libdirs=lib/iphone

So, having combined these 2 changes all works great now :)

Thanks!

**Comment by faizann** [comment]
Yeah for sure these changes to mkf were necessary.

When I did android version, I changed default config to use Android. I made all changes using DeployTool and MKB file. I should have created a separate config for Android instead of Default one. In next code, I will make it cleaner.
